version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    ports:
      - "5000:5000"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: python fastapi_app.py
    ports:
      - "8000:8000"